services:
  - type: web
    name: upscrolling-app
    env: docker
    plan: free
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_ENV
        value: production
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: aws-1-ap-south-1.pooler.supabase.com
      - key: DB_PORT
        value: 6543
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres.nlcudpstockcjewxmadv
      - key: DB_PASSWORD
        sync: false
